IMG_SIZE_OPTION_KEY_NAME = "img_size_option"
TYPE_OPTION_KEY_NAME = "type_option"
TYPE_OPTION_TXT_KEY = '0'
TYPE_OPTION_IMG_KEY = '1'
LAST_SELECTED_TREE_ID_NAME = 'last_selected_tree_id'
LAST_LIST_ORDER_BY_COLUMN = 'last_list_order_by_column'
LAST_LIST_SORT_ORDER_BY = 'last_list_sort_order_by'
TOKEN_LIMIT = 8000
PER_PAGE_COUNT_TXT = 20
PER_PAGE_COUNT_IMG = 10
USER_NAME = "user"
ASSISTANT_NAME = "assistant"
DISPLAY_USER_NAME = "user"
DISPLAY_ASSISTANT_NAME = "assistant"
BROKEN_IMAGE = "res/icons/broken_img.png"   # Path to open folder icon
OPEN_FOLDER_IMAGE = "res/icons/folder_open.png"   # Path to open folder icon
CLOSED_FOLDER_IMAGE = "res/icons/folder_close.png" # Path to closed folder icon