IMG_SIZE_OPTION_KEY_NAME = "img_size_option"
TYPE_OPTION_KEY_NAME = "type_option"
TYPE_OPTION_TXT_KEY = '0'
TYPE_OPTION_IMG_KEY = '1'
LAST_SELECTED_TREE_ID_NAME = 'last_selected_tree_id'
TOKEN_LIMIT = 8000
USER_NAME = "user"
ASSISTANT_NAME = "assistant"
DISPLAY_USER_NAME = "user"
DISPLAY_ASSISTANT_NAME = "assistant"
OPEN_FOLDER_IMAGE = "res/icons/folder.png"   # Path to open folder icon
CLOSED_FOLDER_IMAGE = "res/icons/folder.png" # Path to closed folder icon